### ISSUE TITLE
LHS content overspill on articles

### ISSUE THREAD

**Issue by petecooper** [philwareham/textpattern-bootstrap#208]
e.g. https://bootstrap.philwareham.co.uk/BootstrapforTextpatternDesignPatterns

Body content appears to spill over on the left side. Navbar OK, so presumably a snag with the main content `div`s somewhere.

Screenshots from Safari and Chrome.

![screen shot 2018-12-13 at 12 04 03](https://user-images.githubusercontent.com/226578/49937674-6cb09f80-fecf-11e8-8bef-539d41f4c9a7.png)
<img width="1557" alt="screen shot 2018-12-13 at 12 03 58" src="https://user-images.githubusercontent.com/226578/49937675-6d493600-fecf-11e8-9ded-a797eb7704c3.png">

**Comment by philwareham** [comment]
Ah yes, this repo is still a work-in-progress. Not had much time to continue with building it recently. It's on my list of todo's eventually.

**Comment by petecooper** [comment]
No worries, close it if you like!
